### PR TITLE
Managing Student Profiles

### PR DESCRIPTION
**Pull request by KD54321**
Added the front end for managing student profile.
Added the Upload resume button
The backend does not work yet.

### CODE REVIEW

**Comment by Razvan-Alexandru** [comment]
Don't merge with main.
Please change the target branch.

**Comment by arcvelit** [comment]
Update on this? Can the target branch be updated?

**Comment by arcvelit** [comment]
@Razvan-Alexandru need your advice on this, to which branch should we merge it to? And should we create a new one for it since you can't merge FROM and TO?

**Review by Razvan-Alexandru — CHANGES_REQUESTED** [review]
Change the HTML into a typescript or javascript code using react

**Comment by KD54321** [comment]
Changed the file to javascript using react. Changes can be found in AddedManagingStudentProfile #54

**Pull request closed without merging**
