### PR TITLE
Pushing the code for the headhunter including the styling

### PR DESCRIPTION
**Pull request by wam82**
Pushing the code for the headhunter

### CODE REVIEW

**Review by Amir8Abdullah — COMMENTED** [review]
Why is it showing all lines have been modified even though they are all the same. This is for every page. Though I understand the Headhunter.css and HeadhunterHome.js. JobApplicantsDetailsforHeadhunter.js and they seem good.

**Comment by wam82** [comment]
I think it's due to the fact that the files don't have the same signature or something. But since it's the same lines of codes we should be fine

**Comment by Amir8Abdullah** [comment]
Yeah It looks like it has to do with mac and windows compatibility as the code is the same everywhere. I approve.

**Review by Amir8Abdullah — APPROVED** [review]
As checked with William. The excessive amount of line changes ahs to do something with mac and windows. The only pages that we actually changes were: HeadHunter.css, HeadhunterHome.js was added and JobApplicantDetailsForHeadhunter.js. I approve these changes.

**Pull request merged**
